/**
 * @openeditor-premium/export-docx — Phase 19.5 (DOCX half).
 *
 * Premium: export editor content to a real Microsoft Word .docx — OOXML
 * (WordprocessingML) generated by hand, packaged in a zero-dependency
 * STORE-method ZIP. No JSZip, no docx library. Gated on 'export.docx'.
 *
 *   const host = await createPremiumHost({ license, keys });
 *   editor.plugins.install(createExportDocxPlugin(host, { title: 'Report' }));
 *   // → toolbar button + editor.exportDocx() + editor.buildDocxBytes()
 *
 * Config (install-time, editor._config.exportDocx, or per-call): title.
 * Known v1 limitations (documented in README): images render as caption
 * placeholders, links render as underlined text (no w:hyperlink parts yet).
 */
import { gatePremiumPlugin } from '@openeditor-premium/runtime';
import { rawExportDocxSpec } from './export-docx-plugin.js';

/** The registered feature id this package requires. */
export const FEATURE_ID = 'export.docx';

/**
 * @param {object} host   a resolved createPremiumHost() result
 * @param {object} [config] default export options ({ title })
 * @returns {object} installable plugin spec (active or graceful-degrade stub)
 */
export function createExportDocxPlugin(host, config = {}) {
  return gatePremiumPlugin(host, FEATURE_ID, rawExportDocxSpec(config));
}

export { bodyXml, escapeXml } from './ooxml-body.js';
export { buildDocx } from './docx-parts.js';
export { zipStore } from './zip-store.js';
