/**
 * extract-css.mjs — 17.2: build the static CSS bundle (dist/open-editor.css).
 *
 * Strategy: boot a REAL editor with every shipped plugin inside jsdom. jsdom
 * lacks constructable stylesheets, so injectStyleOnce() takes its <style>-tag
 * fallback — every stylesheet the editor would inject at runtime lands in the
 * DOM, in exact runtime cascade order (order matters: e.g. the fullscreen
 * !important fix exists because of a cascade tie). We then harvest the tags.
 *
 * Belt-and-braces: after booting, every `*-styles.js` module under src/ is
 * imported and each exported inject*(doc) function is called — this catches
 * styles that only inject lazily (first dialog open, etc.). The once-guard
 * makes double-injection impossible, so order stays runtime-faithful for
 * everything the boot already injected.
 *
 * Consumers using this file set `styleInjection: false`-equivalent (CSP docs)
 * or simply load it for SSR paint-before-hydrate.
 */
import { JSDOM } from 'jsdom';
import { readdirSync, statSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath, pathToFileURL } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC = join(__dirname, '..', 'src');

// jsdom globals so editor + plugin modules can boot.
const dom = new JSDOM('<!doctype html><html><head></head><body><div id="host"></div></body></html>', {
  url: 'http://localhost/',
  pretendToBeVisual: true,
});
// defineProperty because Node ≥21 ships own getter-only globals (navigator).
for (const [k, v] of Object.entries({
  window: dom.window,
  document: dom.window.document,
  navigator: dom.window.navigator,
  HTMLElement: dom.window.HTMLElement,
  Node: dom.window.Node,
  getComputedStyle: dom.window.getComputedStyle,
  requestAnimationFrame: (fn) => setTimeout(fn, 0),
  cancelAnimationFrame: (id) => clearTimeout(id),
})) {
  Object.defineProperty(globalThis, k, { value: v, writable: true, configurable: true });
}

const core = await import(pathToFileURL(join(SRC, 'index.js')).href);

// 1. Boot a full editor — every plugin factory exported from the index.
const editor = new core.OpenEditor('#host', { theme: 'light' });
for (const [name, fn] of Object.entries(core)) {
  if (name.startsWith('create') && name.endsWith('Plugin') && typeof fn === 'function') {
    try { editor.plugins.install(fn()); } catch (e) {
      console.warn(`[extract-css] plugin ${name} failed to install in jsdom: ${e.message}`);
    }
  }
}

// 1b. The shared UI primitives (modal / tooltip / context-menu) inject their
// styles LAZILY on first open — a plain boot never triggers them (found when
// the first extraction shipped without oe-modal/tooltip/menu-styles). Exercise
// each once so their styles land in true runtime order.
try { editor.ui.modal.open({ title: 'x', body: 'x' }); editor.ui.modal.close(); } catch (e) { console.warn('[extract-css] modal exercise failed:', e.message); }
try {
  const probe = dom.window.document.createElement('button');
  dom.window.document.body.appendChild(probe);
  editor.ui.tooltip.show(probe, 'x');
  editor.ui.tooltip.hide();
} catch (e) { console.warn('[extract-css] tooltip exercise failed:', e.message); }
try {
  editor.ui.contextMenu.show(0, 0, [{ label: 'x', onClick() {} }]);
  editor.ui.contextMenu.hide();
} catch (e) { console.warn('[extract-css] context-menu exercise failed:', e.message); }

// 2. Belt-and-braces: import every *-styles.js and call its inject functions.
function stylesModules(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry);
    if (statSync(p).isDirectory()) out.push(...stylesModules(p));
    else if (entry.endsWith('-styles.js')) out.push(p);
  }
  return out;
}
for (const file of stylesModules(SRC)) {
  const mod = await import(pathToFileURL(file).href);
  for (const [name, fn] of Object.entries(mod)) {
    if (typeof fn === 'function' && /^inject/i.test(name)) {
      try { fn(dom.window.document); } catch (e) {
        console.warn(`[extract-css] ${name} (${file}) failed: ${e.message}`);
      }
    }
  }
}

// 3. Harvest, in DOM (== injection) order.
const tags = [...dom.window.document.querySelectorAll('style[id]')];
if (tags.length === 0) throw new Error('extract-css: no styles harvested — did injectStyleOnce change?');
const banner = `/*!\n * Open Editor — static CSS bundle (generated by scripts/extract-css.mjs)\n * For SSR / strict-CSP consumers. Runtime style injection is the default path\n * and remains CSP-safe via constructable stylesheets — this file is optional.\n */\n`;
const css = tags.map((t) => `/* ── ${t.id} ── */\n${t.textContent.trim()}`).join('\n\n');

mkdirSync(join(__dirname, '..', 'dist'), { recursive: true });
writeFileSync(join(__dirname, '..', 'dist', 'open-editor.css'), banner + css + '\n');
console.log(`[extract-css] wrote dist/open-editor.css — ${tags.length} style blocks, ${(banner + css).length} bytes`);
editor.destroy();
