export { VERSION } from './version.js';
export { OpenEditor } from './editor.js';
export { EventEmitter } from './events/event-emitter.js';
export { Logger } from './logger/logger.js';
export { ShortcutManager } from './shortcuts/shortcut-manager.js';
export { EditorState } from './state/editor-state.js';
export { sanitize, normalizeEncoding, normalizeStructure, normalizeTextNodes } from './sanitizer/sanitizer.js';
export { debounce } from './utils/debounce.js';
export { SelectionManager } from './selection/selection-manager.js';
export { walkUp, getClosestTag, getParentBlock, isInsideTag, getDeepestNode } from './selection/range-utils.js';
export { copyToClipboard, getClipboardText, isClipboardApiAvailable } from './utils/clipboard.js';
export { CommandManager } from './commands/command-manager.js';
export { HistoryManager } from './history/history-manager.js';
export { ModalManager } from './ui/modal-manager.js';
export { TooltipManager } from './ui/tooltip-manager.js';
export { ContextMenuManager } from './ui/context-menu-manager.js';
export { PluginManager } from './plugins/plugin-manager.js';
export { createTestEditor } from './testing/test-harness.js';
export { imagePlugin, createImagePlugin } from './plugins/image/image-plugin.js';
export { linkPlugin, createLinkPlugin } from './plugins/link/link-plugin.js';
export { tablePlugin, createTablePlugin } from './plugins/table/table-plugin.js';
export { spellcheckPlugin, createSpellcheckPlugin } from './plugins/spellcheck/spellcheck-plugin.js';
export { specialCharsPlugin, createSpecialCharsPlugin } from './plugins/chars/special-chars-plugin.js';
export { emojiPlugin, createEmojiPlugin } from './plugins/emoji/emoji-plugin.js';
export { previewPlugin, createPreviewPlugin } from './plugins/preview/preview-plugin.js';
export { formatPainterPlugin, createFormatPainterPlugin } from './plugins/format-painter/format-painter-plugin.js';
export { resizeEditorPlugin, createResizeEditorPlugin } from './plugins/resize-editor/resize-editor-plugin.js';
export { findReplacePlugin, createFindReplacePlugin } from './plugins/find-replace/find-replace-plugin.js';
export { mediaPlugin, createMediaPlugin } from './plugins/media/media-plugin.js';
export { codeBlockPlugin, createCodeBlockPlugin } from './plugins/code-block/code-block-plugin.js';
export { sourcePlugin, createSourcePlugin } from './plugins/source/source-plugin.js';
export { slashCommandPlugin, createSlashCommandPlugin } from './plugins/slash-command/slash-command-plugin.js';
export { autoformatPlugin, createAutoformatPlugin } from './plugins/autoformat/autoformat-plugin.js';
export { mentionsPlugin, createMentionsPlugin } from './plugins/mentions/mentions-plugin.js';
export { blockDragPlugin, createBlockDragPlugin } from './plugins/block-drag/block-drag-plugin.js';
export { todoListPlugin, createTodoListPlugin } from './plugins/todo-list/todo-list-plugin.js';
// 17.11 — UI locale packs. Named exports so bundlers tree-shake unused
// languages via the ESM module tree (a core-only import drops all of them);
// also reachable as subpaths: '@open-editor-hq/core/locales/es'.
export { es as localeEs } from './locales/es.js';
export { fr as localeFr } from './locales/fr.js';
export { de as localeDe } from './locales/de.js';
export { ar as localeAr } from './locales/ar.js';
